language:
  - python
install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
before_script: 
  - python manage.py migrate
script:
  - flake8 --max-line-length=92
  - black --check .
after_script:
  - coveralls